'use client'

import React from 'react'
import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Badge,
  BadgeAlert,
  BarChart3,
  BadgeCheck,
  BadgeHelp,
  BadgeInfo,
  BadgePlus,
  Bed,
  BedDouble,
  Bell,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  CalendarX,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  Copy,
  CreditCard,
  Database,
  DoorOpen,
  Download,
  Eye,
  FileCheck,
  FileEdit,
  FilePlus,
  FileSpreadsheet,
  FileText,
  Filter,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  Heart,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Hospital,
  Info,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  ListOrdered,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  Minimize2,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Phone,
  Pill,
  Pin,
  Play,
  Plus,
  PlusCircle,
  Printer,
  QrCode,
  Radio,
  Receipt,
  RefreshCw,
  RotateCcw,
  Save,
  Scan,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sliders,
  Sparkles,
  Square,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Tablet,
  Tag,
  TestTube,
  Thermometer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Utensils,
  UtensilsCrossed,
  Video,
  Volume2,
  VolumeX,
  Wallet,
  X,
  XCircle,
  Zap,
  LucideIcon as LucideIconType,
} from 'lucide-react'

// Comprehensive dictionary mapping material symbol / semantic icon names to Lucide icons
const ICON_MAP: Record<string, LucideIconType> = {
  // Navigation & Core
  home: Home,
  dashboard: LayoutDashboard,
  space_dashboard: LayoutDashboard,
  menu: Menu,
  close: X,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  search: Search,
  settings: Settings,
  logout: LogOut,
  notifications: Bell,
  bell: Bell,
  help: HelpCircle,
  info: Info,
  star: Star,
  check: Check,
  check_circle: CheckCircle2,
  done: Check,
  done_all: CheckCircle2,
  refresh: RefreshCw,
  sync: RefreshCw,
  error: AlertCircle,
  error_med: AlertOctagon,
  warning: AlertTriangle,
  priority_high: AlertCircle,
  bolt: Zap,
  zap: Zap,
  sparkles: Sparkles,

  // Healthcare, Clinical & Doctors
  stethoscope: Stethoscope,
  vital_signs: HeartPulse,
  heart_pulse: HeartPulse,
  cardiology: HeartPulse,
  favorite: Heart,
  monitor_heart: HeartPulse,
  ecg_heart: Activity,
  clinical_notes: ClipboardList,
  prescriptions: Pill,
  pill: Pill,
  medication: Pill,
  local_pharmacy: Pill,
  medical_services: Stethoscope,
  hospital: Hospital,
  local_hospital: Hospital,
  doctor: Stethoscope,
  nurse: HeartPulse,
  bed: BedDouble,
  airline_seat_individual_suite: BedDouble,
  ward: BedDouble,
  inpatient: Bed,
  transfer_within_a_station: ArrowLeftRight,
  thermometer: Thermometer,
  device_thermostat: Thermometer,
  air: Radio,
  pulmonology: Activity,
  syringe: Syringe,
  medical_information: FileText,

  // Lab & Diagnostics
  biotech: FlaskConical,
  science: FlaskConical,
  flask: FlaskConical,
  test_tube: TestTube,
  microscope: FlaskConical,
  lab: FlaskConical,
  assignment: ClipboardList,
  edit_note: FileEdit,
  tune: Sliders,
  send: Send,

  // Admin, Front Desk & Users
  person: User,
  people: Users,
  users: Users,
  group: Users,
  groups: Users,
  personal_injury: UserX,
  manage_accounts: UserCog,
  domain: Building2,
  bar_chart: BarChart3,
  health_and_safety: ShieldCheck,
  person_search: Search,
  person_add: UserPlus,
  person_pin: MapPin,
  person_off: UserMinus,
  badge: Badge,
  admin_panel_settings: ShieldCheck,
  security: Shield,
  shield: Shield,
  lock: Lock,
  meeting_room: DoorOpen,

  // Appointments, Queue, Calendar & Communication
  calendar_today: Calendar,
  calendar_month: Calendar,
  event: Calendar,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  queue: ListOrdered,
  chat: MessageSquare,
  chat_bubble: MessageSquare,
  add_circle: PlusCircle,
  add: Plus,
  play_arrow: Play,
  campaign: Bell,
  schedule: Clock,
  history: History,
  confirmation_number: Receipt,

  // Billing, POS, Finance & Commerce
  receipt: Receipt,
  receipt_long: Receipt,
  point_of_sale: CreditCard,
  credit_card: CreditCard,
  payments: CreditCard,
  add_card: CreditCard,
  attach_money: CreditCard,
  account_balance_wallet: Wallet,
  wallet: Wallet,
  sell: Tag,
  inventory: Package,
  inventory_2: Package,
  shopping_cart: ShoppingCart,
  local_shipping: Truck,

  // Canteen & Dining
  restaurant: Utensils,
  fastfood: Utensils,
  nutrition: Utensils,
  room_service: UtensilsCrossed,
  restaurant_menu: FileSpreadsheet,
  no_food: Utensils,

  // Emergency & SOS
  emergency: AlertOctagon,
  sos: AlertOctagon,
  ambulance: Truck,

  // Document & Voice
  mic: Mic,
  mic_off: MicOff,
  print: Printer,
  download: Download,
  upload: Upload,
  mail: Mail,
  phone: Phone,
  open_in_new: ArrowRight,
  sync_saved_locally: CheckCircle2,
  progress_activity: RefreshCw,
  construction: Layers,
}

export type IconName = string

export interface ClinivaIconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName
  size?: number | string
  className?: string
  strokeWidth?: number
}

/**
 * Global Cliniva OS Unified Healthcare Icon component.
 * Renders modern, geometric, clean-outline Lucide SVG icons with a consistent 1.5px stroke width.
 */
export default function ClinivaIcon({
  name,
  size = 18,
  className = '',
  strokeWidth = 1.5,
  ...props
}: ClinivaIconProps) {
  const normalizedKey = (name || '').trim().toLowerCase()
  const IconComponent = ICON_MAP[normalizedKey] || ICON_MAP[normalizedKey.replace(/-/g, '_')] || Activity
  const sizeNum = typeof size === 'string' ? parseInt(size, 10) || 18 : size

  return (
    <IconComponent
      width={sizeNum}
      height={sizeNum}
      strokeWidth={strokeWidth}
      className={`inline-block flex-shrink-0 ${className}`}
      {...props}
    />
  )
}
